- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true